echoSql: False
rootPath: /api/review-service
databaseUri: sqlite:////app/data/reviews.db

apm:
  enabled: 'true'
  serverUrl: 'https://elk.onintranet.com:8200'
  verifyServerCert: 'false'
  log:
    ecsFormatting: 'off'
    file: 'demo-review-service.log'
    fileSize: '16mb'
    level: 'info'
    recording: 'true'

service:
  type: ClusterIP
  port: 80
